<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.Maui" Version="14.1.0" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.41" />
  </ItemGroup>
</Project>
